/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedCoinsRouteImport } from './routes/_authenticated/coins'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicSoleaspayWebhookRouteImport } from './routes/api/public/soleaspay-webhook'
import { Route as AuthenticatedChannelIdRouteImport } from './routes/_authenticated/channel.$id'
import { Route as ApiPublicStreamSplatRouteImport } from './routes/api/public/stream.$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoinsRoute = AuthenticatedCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSoleaspayWebhookRoute =
  ApiPublicSoleaspayWebhookRouteImport.update({
    id: '/api/public/soleaspay-webhook',
    path: '/api/public/soleaspay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChannelIdRoute = AuthenticatedChannelIdRouteImport.update({
  id: '/channel/$id',
  path: '/channel/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicStreamSplatRoute = ApiPublicStreamSplatRouteImport.update({
  id: '/api/public/stream/$',
  path: '/api/public/stream/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/coins': typeof AuthenticatedCoinsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/channel/$id': typeof AuthenticatedChannelIdRoute
  '/api/public/soleaspay-webhook': typeof ApiPublicSoleaspayWebhookRoute
  '/api/public/stream/$': typeof ApiPublicStreamSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/coins': typeof AuthenticatedCoinsRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/channel/$id': typeof AuthenticatedChannelIdRoute
  '/api/public/soleaspay-webhook': typeof ApiPublicSoleaspayWebhookRoute
  '/api/public/stream/$': typeof ApiPublicStreamSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/coins': typeof AuthenticatedCoinsRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/channel/$id': typeof AuthenticatedChannelIdRoute
  '/api/public/soleaspay-webhook': typeof ApiPublicSoleaspayWebhookRoute
  '/api/public/stream/$': typeof ApiPublicStreamSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/admin'
    | '/browse'
    | '/coins'
    | '/plans'
    | '/channel/$id'
    | '/api/public/soleaspay-webhook'
    | '/api/public/stream/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/admin'
    | '/browse'
    | '/coins'
    | '/plans'
    | '/channel/$id'
    | '/api/public/soleaspay-webhook'
    | '/api/public/stream/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/browse'
    | '/_authenticated/coins'
    | '/_authenticated/plans'
    | '/_authenticated/channel/$id'
    | '/api/public/soleaspay-webhook'
    | '/api/public/stream/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicSoleaspayWebhookRoute: typeof ApiPublicSoleaspayWebhookRoute
  ApiPublicStreamSplatRoute: typeof ApiPublicStreamSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coins': {
      id: '/_authenticated/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof AuthenticatedCoinsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/soleaspay-webhook': {
      id: '/api/public/soleaspay-webhook'
      path: '/api/public/soleaspay-webhook'
      fullPath: '/api/public/soleaspay-webhook'
      preLoaderRoute: typeof ApiPublicSoleaspayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/channel/$id': {
      id: '/_authenticated/channel/$id'
      path: '/channel/$id'
      fullPath: '/channel/$id'
      preLoaderRoute: typeof AuthenticatedChannelIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/stream/$': {
      id: '/api/public/stream/$'
      path: '/api/public/stream/$'
      fullPath: '/api/public/stream/$'
      preLoaderRoute: typeof ApiPublicStreamSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCoinsRoute: typeof AuthenticatedCoinsRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedChannelIdRoute: typeof AuthenticatedChannelIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCoinsRoute: AuthenticatedCoinsRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedChannelIdRoute: AuthenticatedChannelIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicSoleaspayWebhookRoute: ApiPublicSoleaspayWebhookRoute,
  ApiPublicStreamSplatRoute: ApiPublicStreamSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
